# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7da580c8652f60fad2f2a977fb2849caf4be0eb542ce1a18f0a634b0e5fce17311cfb30b7c2458b524372b58513aabd5f67e0af0dc57ba6bc25a0294acb031b7

test:
  secret_key_base: 4cbfd4c899c641c985b0f27a1f32871b2a2cc9ecf4962ba40956764e701690a079a5f280a190643faa07e3058026147ef5f502b16d1499865c89863f912f53ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
